catalog.demo.repo=jeka-dev/demo
catalog.demo.desc=Applications and tools that demonstrate Jeka capabilities.

catalog.djeang.repo=djeang
catalog.djeang.desc=Applications and tools made by the author of JeKa.

catalog.thirdparty.repo=jeka-dev/thirdparty-catalog
catalog.thirdparty.desc=Applications and tools made by various authors

app.cowsay.repo=https://github.com/jeka-dev/demo-cowsay
app.cowsay.desc=Java port or the Cowsay famous CLI.
app.cowsay.type=CLI
app.cowsay.native=true

app.demo-springboot-angular.repo=https://github.com/jeka-dev/demo-project-springboot-angular
app.demo-springboot-angular.desc=Manage a list of users. Written in Springboot and Angular
app.demo-springboot-angular.type=SERVER-UI
app.demo-springboot-angular.native=true


app.demo-springboot-reactjs.repo=https://github.com/jeka-dev/demo-build-conventions-consumer
app.demo-springboot-reactjs.desc=A Springboot app with reactJS front-end to manage coffee shops.
app.demo-springboot-reactjs.type=SERVER-UI
app.demo-springboot-reactjs.native=true

app.demo-quarkus-maven.repo=https://github.com/jeka-dev/demo-maven-jeka-quarkus.git
app.demo-quarkus-maven.desc=Manage a basket of fruit. Written with Quarkus, built with Maven.
app.demo-quarkus-maven.type=SERVER-UI


